name: Hello World

on:
  workflow_dispatch:

env:
    MY_MESSAGE: "Hallo World"

jobs:
    helloWorld:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo "Hello ${MY_MESSAGE}"
            - name: say goodbye
              run: echo "Byby ${MY_MESSAGE}"
