name: Hello World

# here we define the events which trigger the action
on:
  workflow_dispatch:

# here we can define environment variables as well as sensitive things like e.g. db-passwords
env:
    MY_MESSAGE: "World"
    MY_SECRET_MESSAGE:  ${{secrets.MY_SECRET_MESSAGE}}
    NO_SECRET_VARIABLE: ${{ vars.NO_SECRET_VAR }}

jobs:
    # the name/key of the job
    helloWorld:
      # the base image of the virtual machine to use
      runs-on: ubuntu-latest
      steps:
        - name: say hello
          run: echo "Hello ${MY_MESSAGE}"
        - name: very hush hush
          run: echo "${MY_SECRET_MESSAGE}"
        - name: nicht geheim
          run: echo "${NO_SECRET_VARIABLE}"
    goodbye:
      runs-on: ubuntu-latest
      steps:
        - name: say goodbye
          run: echo "Bye bye ${MY_MESSAGE}"
    lookaround:
      runs-on: ubuntu-latest
      steps:
        - name: ls
          run: ls
        - name: pwd
          run: pwd
    withaction:
      runs-on: ubuntu-latest
      steps:
        - name: Check out source repository
          run: actions/checkout@v4
        - name: ls
          run: ls
        - name: pwd
          run: pwd
