name: Hello World

on:
  workflow_dispatch:

env:
    MY_MESSAGE: "World"

jobs:
    helloWorld:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo "Hello ${MY_MESSAGE}"
            - name: say goodbye
              run: echo "Bye bye ${MY_MESSAGE}"
