name: Hello World

on:
  workflow_dispatch:

env:
    MY_MESSAGE: "World"
    MY_SECRET_MESSAGE:  ${{secrets.MY_SECRET_MESSAGE}}

jobs:
    helloWorld:
        runs-on: ubuntu-latest
        steps:
            - name: say hello
              run: echo "Hello ${MY_MESSAGE}"
            - name: say goodbye
              run: echo "Bye bye ${MY_MESSAGE}"
            - name: very hush hush
              run: echo "${MY_SECRET_MESSAGE}"
